title: "sans merde"
#author: "Default Author Name"
description: "texts on social sciences methodology, epistemology, knowledge politics, anti-philosophy, and anti-authoritarian/anti-fascist activism" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "sans_merde@proton.me"
twitter_username: "liya_lift"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

#fonts:

 #primary: Roboto Slab

 #secondary: Helvetica

rss: rss

google_analytics:
  - G-Y2K75XNM3T

kramdown:
  syntax_highlighter_opts:
    disable: true

#gems:
#- jekyll/tagging
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-titles-from-headings
#  - jekyll-tagging

#tag_page_layout: tag
#tag_page_dir: blog/tags
#tag_permalink_style: pretty

titles_from_headings:
  enabled:     true
  strip_title: true
  #collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      strip_title: true

header_pages:
  - archive.md
 

